# Upstream servers for your Node.js APIs
upstream api1 {
    server api1:8001;  # Replace with the IP address and port of your first Node.js API
}

server {
    listen 80;
    server_name financetrt.com www.financetrt.com api.financetrt.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name financetrt.com;

    ssl_certificate /etc/letsencrypt/live/financetrt.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/financetrt.com/privkey.pem;

    location / {
        # Redirect to the subdomain's home page
        return 301 https://api.financetrt.com;
    }
}


server {
    listen 443 ssl;
    server_name www.financetrt.com;

    ssl_certificate /etc/letsencrypt/live/www.financetrt.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.financetrt.com/privkey.pem;

    location / {
        # Redirect to the subdomain's home page
        return 301 https://api.financetrt.com;
    }
}

server {
   listen 443 ssl;
   server_name api.financetrt.com;
   
   ssl_certificate /etc/letsencrypt/live/api.financetrt.com/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/api.financetrt.com/privkey.pem;
   
   location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://api1;
        proxy_redirect off;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'PUT, POST, PATCH, DELETE, GET';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }
}
